apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloapp-v1
    track: stable
  name: helloapp-v1
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      app: helloapp-v1
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloapp
        track: stable
    spec:
      containers:
      - image: 240796/stable-version:latest
        imagePullPolicy: IfNotPresent
        name: stable-version
      restartPolicy: Always
