apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-v1
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloapp
        version: v1
        track: stable
    spec:
      containers:
      - image: 240796/helloapp:v1
        imagePullPolicy: IfNotPresent
        name: helloapp-v1
      restartPolicy: Always
